### ISSUE TITLE
Updates to the start rotation property not reflected in-game

### ISSUE THREAD

**Issue by Jaden909** [Moonzel/Godot-PerfBullets#10]
![image](https://github.com/Moonzel/Godot-PerfBullets/assets/118631735/2fea0ae5-0343-4331-a0d5-8f96cf2ea6a0)

I have this code that on left click, sets the spawner's start rotation to the current rotation of the gun and then shoots the gun. The property is updated, but bullets are still shot in the direction that start rotation was initially set to. Is this unintended behavior or is there another way to change the direction bullets shoot?

**Comment by Moonzel** [comment]
Thank you for bringing this to my attention. I am currently testing the fix for this and will release it at some point today.

**Comment by Moonzel** [comment]
Let me know if this does not solve the issue. Have a good day!
