### ISSUE TITLE
Can this library work with regular enemies?

### ISSUE THREAD

**Issue by wayjack** [Moonzel/Godot-PerfBullets#5]
I am looking for a plugin that can spawn massive amounts of enemies moving to the player (similar to Vampire Survivors). I know this library is intended for bullets but can it work for enemies too?

**Comment by Moonzel** [comment]
I would say that yes, but with modifications. The code itself has high performance and could work for that type of game, however, in its current state, it would be difficult to do that. I have a feeling it could be done, but I do not know your exact use case. I would suggest trying to build off of my plugin if you wanted to try that. Best of luck!
