### ISSUE TITLE
emit(): Space state in inaccessible

### ISSUE THREAD

**Issue by Wazard** [Moonzel/Godot-PerfBullets#7]
this may be my own falut, I'm new to godot and was trying out your plugin but, after setting everything up as the tutorial, i'm getting this error:
![immagine](https://github.com/Moonzel/Godot-PerfBullets/assets/34705162/5d6f842c-28a9-47e9-bdfd-2e605c1f8ee4)

**Comment by Moonzel** [comment]
I just tried it on my end, and I am not getting this error, nor have I seen it before. Is the PatternManager still having the Spawner spawn bullets, and are the bullets colliding with the player as expected? I may be able to debug this if I have more information. Thank you!

**Comment by Wazard** [comment]
https://github.com/Moonzel/Godot-PerfBullets/assets/34705162/95c0f6a3-caf6-4525-a08c-588d390286ad

**Comment by Wazard** [comment]
https://youtu.be/WFHCbYvjqb4

Thanks GitHub

**Comment by Moonzel** [comment]
I could not notice what you did wrong that would cause this error. This is the first time I have seen it. Could you try re-downloading it straight from GitHub? Please let me know if this is still happening because I would love to get this solved.

**Comment by Moonzel** [comment]
Since I have not been able to recreate this, and I have not heard from you for some time, I am closing this issue. Please open another one if the problem still exists.
