### ISSUE TITLE
fireRate set in code not reflected in-game

### ISSUE THREAD

**Issue by greenguy77** [Moonzel/Godot-PerfBullets#9]
![image](https://github.com/Moonzel/Godot-PerfBullets/assets/155271860/73a73112-7331-4617-a817-8e09e0987fde)
![image](https://github.com/Moonzel/Godot-PerfBullets/assets/155271860/1e2d7259-733d-4ae4-ba85-3df8653a983b)
In the code I'm able to set various values for the spawner, but the fireRate value does not update the fireRate of the actual spawner.
You can read/write values to the fireRate, but the spawner in game will continue firing at the firerate that was initially set. In the second image you can see a spawner that had the following values when placed:
fireRate= 0.1
BulletsPerRadius = 1
bulletType.maxLifetime = 10

These values were updated in the code, and all are reflected in-game with the exception of fireRate. Additionally the function set_fireRate() does not exist (Or at least I can't access it). The documentation declares that all properties have a getter/setter function built in, but I have not been able to make these work (I imagine if I could use the dedicated setter for this property, if it exists, then this issue wouldn't exist)

And while I'm here, there's some minor issues I have that doesn't deserve their own requests:
![image](https://github.com/Moonzel/Godot-PerfBullets/assets/155271860/c12dedb8-d345-49ca-be7b-ed1734f176bc)
When hovering over properties in the spawner settings it doesn't provide descriptions of what the properties do. I instead have to flip back to the documentation if I haven't memorized that information. I don't know how easy this is to resolve, since the spawners are written in c++ and thus Godot might not be able to read their in-built documentation, but it would be nice to have.

![image](https://github.com/Moonzel/Godot-PerfBullets/assets/155271860/0d3617c9-15af-4318-8915-9ac6340f1bf8)
Every time I build my project I get these errors. They don't actually effect anything. Everything builds fine, and auto-complete works, but it's a minor annoyance I wish I didn't have to deal with. I know this might be a major pain to fix, so I understand not bothering with it.

**Comment by Moonzel** [comment]
Hello @greenguy77! Thanks for letting me know about this. With your first problem with `fireRate`, that is fixed now. I forgot to update the value of the timer's `wait_time` property. 

Secondly, I do not think there is a way at the moment to add documentation with GDExtension, but if there is, I will add it. I think this would really help with plug-ins across the board, but if it exists, I do not know how to do it.

Last, that seems to be a bug with Godot that I cannot solve. I would encourage you to make a Issue on the Godot Github page for this. 

I will be editing documentation and releasing the update tonight along with a new Spawner mode, so please reach out if you have problems with anything else!
